sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.11"
before_script:
  - npm install -g grunt-cli
  - wget https://github.com/mgreter/sass2scss/archive/v1.0.2.tar.gz
  - tar zxf v1.0.2.tar.gz
  - cd sass2scss-1.0.2/
  - make
  - export PATH=$PATH:$PWD
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"
