sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "3"
  - "4"
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "3"
before_script:
  - npm install -g grunt-cli
  - wget https://github.com/mgreter/sass2scss/archive/v1.0.3.tar.gz
  - tar zxf v1.0.3.tar.gz
  - cd sass2scss-1.0.3/
  - make
  - cd ..
  - export PATH=$PATH:$PWD/sass2scss-1.0.3
  - sass2scss --version
