sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "iojs"
before_script:
  - npm install -g grunt-cli
  - wget https://github.com/mgreter/sass2scss/archive/v1.0.2.tar.gz
  - tar zxf v1.0.2.tar.gz
  - cd sass2scss-1.0.2/
  - make
  - cd ..
  - export PATH=$PATH:$PWD/sass2scss-1.0.2
  - sass2scss --version
